# Generated by Django 4.1.5 on 2023-01-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Отслеживать?'),
        ),
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Отслеживать?'),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='strahovka',
            field=models.DateField(verbose_name='Страховка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tahograf',
            field=models.DateField(verbose_name='Тахограф'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tamogennoye',
            field=models.DateField(verbose_name='Таможенное'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tehosmotr',
            field=models.DateField(verbose_name='Техосмотр'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_card',
            field=models.DateField(verbose_name='Водительское удостоверение'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport',
            field=models.DateField(verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='visa',
            field=models.DateField(verbose_name='Виза'),
        ),
    ]
