# Generated by Django 4.1.5 on 2023-06-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_car_active_driver_active_alter_car_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AddField(
            model_name='car',
            name='cmr_strahovka',
            field=models.DateField(blank=True, null=True, verbose_name='КАСКО'),
        ),
        migrations.AddField(
            model_name='car',
            name='green_card',
            field=models.DateField(blank=True, null=True, verbose_name='Зелёнка'),
        ),
        migrations.AddField(
            model_name='car',
            name='kasko',
            field=models.DateField(blank=True, null=True, verbose_name='КАСКО'),
        ),
        migrations.AlterField(
            model_name='car',
            name='strahovka',
            field=models.DateField(blank=True, null=True, verbose_name='Страховка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tahograf',
            field=models.DateField(blank=True, null=True, verbose_name='Тахограф'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tamogennoye',
            field=models.DateField(blank=True, null=True, verbose_name='Таможенное'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tehosmotr',
            field=models.DateField(blank=True, null=True, verbose_name='Техосмотр'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='visa',
            field=models.DateField(blank=True, null=True, verbose_name='Виза'),
        ),
    ]
