# Generated by Django 4.1.5 on 2023-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_car_options_alter_driver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cmr_strahovka',
            field=models.DateField(blank=True, null=True, verbose_name='CMR-страховка'),
        ),
    ]
