# Generated by Django 4.1.5 on 2023-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_driver_middle_name_alter_car_cmr_strahovka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
    ]
