# Generated by Django 4.1.5 on 2023-06-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_driver_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateField(verbose_name='Дата подачи в страховую')),
                ('polis_number', models.CharField(max_length=10, verbose_name='Страховой полис')),
                ('police_sertificate', models.BooleanField(default=False, verbose_name='Справка с ГАИ?')),
                ('repair_method', models.CharField(blank=True, choices=[('Калькуляция', 'Калькуляция'), ('Сервис', 'Сервис')], max_length=13, null=True, verbose_name='Способ ремонта')),
                ('calculation_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Страховая насчитала по калькуляции')),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Наши расходы по восстановлению (Калькуляция)')),
                ('margin', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='В нашу пользу (Калькуляция)')),
                ('service_name', models.CharField(max_length=50, verbose_name='На какой сервис отправили ТС')),
                ('service_date', models.DateField(verbose_name='Дата отправки на сервис')),
                ('service_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма счета от сервиса')),
                ('final_docs', models.DateField(verbose_name='Дата передачи документов по ремонту в страховую')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты от страховой')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.driver')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesInsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='database/images', verbose_name='Фото')),
                ('insurance_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.insuranceevent')),
            ],
        ),
    ]
