# Generated by Django 4.1.5 on 2023-06-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_insuranceevent_imagesinsuranceevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesinsuranceevent',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='insuranceevent',
            options={'verbose_name': 'Страховой случай', 'verbose_name_plural': 'Страховые случаи'},
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='final_docs',
            field=models.DateField(blank=True, null=True, verbose_name='Дата передачи документов по ремонту в страховую'),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты от страховой'),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки на сервис'),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='service_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='На какой сервис отправили ТС'),
        ),
    ]
