# Generated by Django 4.1.5 on 2023-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_imagesinsuranceevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesinsuranceevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='insuranceevent',
            name='payment_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата оплаты от страховой'),
        ),
    ]
